In [3]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
tf.autograph.set_verbosity(0)

In [4]:
#synthetic datapoints
from sklearn.datasets import make_blobs
centers = [[-5, 2], [-2, -2], [1, 2], [5, -2]]
X_train, y_train = make_blobs(n_samples=2000, centers=centers, cluster_std=1.0,random_state=30)

In [5]:
from tensorflow.keras.losses import SparseCategoricalCrossentropy
model=Sequential([
    Dense(units=25,activation='relu'),
    Dense(units=15,activation='relu'),
    Dense(units=4,activation='linear')
])
model.compile(
    loss=SparseCategoricalCrossentropy(from_logits=True),
    optimizer=tf.keras.optimizers.Adam(0.001)
)

model.fit(X_train,y_train,epochs=10)
    

Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 1.2042
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5226
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2271
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1228
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0858
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0687
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0585
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0530
Epoch 9/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0481
Epoch 10/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0446


In [14]:
prediction = model.predict(X_train)
print(np.argmax(prediction[0]))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
2


In [15]:
print(X_train.shape)

(2000, 2)


In [22]:
for i in range(10):
    print(np.argmax(prediction[i]))

2
0
0
1
2
2
1
0
1
3


In [20]:
#incase you want probabilities
final = tf.nn.softmax(prediction)
print(final)

tf.Tensor(
[[2.7169031e-03 1.8203367e-03 9.4974321e-01 4.5719542e-02]
 [9.9496043e-01 3.2226893e-03 1.8060693e-03 1.0825100e-05]
 [9.6362519e-01 2.7113048e-02 9.0904459e-03 1.7131293e-04]
 ...
 [1.1933160e-03 9.9527401e-01 1.5244792e-03 2.0082272e-03]
 [1.2373425e-06 1.1797137e-04 1.4920356e-03 9.9838877e-01]
 [6.4720791e-03 1.0417715e-03 9.8669410e-01 5.7920180e-03]], shape=(2000, 4), dtype=float32)
