In [7]:
import numpy as np

# ---------------------------------------------------
# 1. Activation function
# ---------------------------------------------------
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# ---------------------------------------------------
# 2. Single dense layer (for-loop version)
# ---------------------------------------------------
def dense(a_in, W, b):
    units = W.shape[1]#neurons
    a_out = np.zeros(units)#output same as no. of neuroans
    for j in range(units):
        z = np.dot(a_in, W[:, j]) + b[j]
        a_out[j] = sigmoid(z)
    return a_out

# ---------------------------------------------------
# 3. Forward propagation through the whole network
# ---------------------------------------------------
def my_sequential(x, W1, b1, W2, b2):
    a1 = dense(x,  W1, b1)   # layer 1 output
    a2 = dense(a1, W2, b2)   # layer 2 output (final prediction)
    return a2

# ---------------------------------------------------
# 4. Predict function (loops over all examples)
# ---------------------------------------------------
def my_predict(X, W1, b1, W2, b2):
    m = X.shape[0]
    p = np.zeros((m, 1))
    for i in range(m):
        p[i, 0] = my_sequential(X[i], W1, b1, W2, b2)
    return p

# ---------------------------------------------------
# 5. Weights (pretrained values from the lab)
# ---------------------------------------------------
W1 = np.array([
    [-8.94,  0.29, 12.89],
    [-0.17, -7.34, 10.79]
])
b1 = np.array([-9.87, -9.28, 1.01])

W2 = np.array([
    [-31.38],
    [-27.86],
    [-32.79]
])
b2 = np.array([15.54])

# ---------------------------------------------------
# 6. Normalization (must match training normalization)
#    Here we hardcode approximate mean/std from the
#    original coffee dataset used in the lab.
# ---------------------------------------------------
def normalize(X, mu, sigma):
    return (X - mu) / sigma

# Example mean/std (replace with norm_l's learned values if available)
mu    = np.array([185.32, 13.31])   # [Temp mean, Duration mean]
sigma = np.array([26.29, 1.5])      # [Temp std,  Duration std]

# ---------------------------------------------------
# 7. Test data
# ---------------------------------------------------
X_test = np.array([
    [200, 13.9],  # positive example (good roast)
    [200, 17]     # negative example (bad roast)
])

X_testn = normalize(X_test, mu, sigma)
print("X_testn =\n", X_testn)

# ---------------------------------------------------
# 8. Run forward propagation / prediction
# ---------------------------------------------------
predictions = my_predict(X_testn, W1, b1, W2, b2)
print("\npredictions =\n", predictions)

# ---------------------------------------------------
# 9. Convert probabilities to decisions
# ---------------------------------------------------
yhat = (predictions >= 0.5).astype(int)
print("\ndecisions =\n", yhat)

X_testn =
 [[0.55838722 0.39333333]
 [0.55838722 2.46      ]]

predictions =
 [[3.22401782e-08]
 [3.22416325e-08]]

decisions =
 [[0]
 [0]]


C:\Users\Muhammad Tahir\AppData\Local\Temp\ipykernel_26260\385475881.py:35: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  p[i, 0] = my_sequential(X[i], W1, b1, W2, b2)
