# Linear regreeison using tensor Flow

In [136]:
import tensorflow as tf
import numpy as np

In [137]:
#data
X_train = np.array([[1.0], [2.0]], dtype=np.float32)
Y_train = np.array([[300.0], [500.0]], dtype=np.float32)

In [138]:
#create neuron
linear_layer = tf.keras.layers.Dense(units=1,activation='linear')

In [139]:
#initiavlzie w (using no of inputs)
a1 = linear_layer(X_train[0].reshape(1,1))

In [140]:
#set w & b
set_w = np.array([[200]])
set_b = np.array([100])
linear_layer.set_weights([set_w, set_b])

In [141]:
#make prediction
prediction = linear_layer(X_train)
print(prediction)

tf.Tensor(
[[300.]
 [500.]], shape=(2, 1), dtype=float32)


# Logistic Neuron

In [142]:
from tensorflow.keras import Sequential

In [143]:
#data
X_train = np.array([0., 1, 2, 3, 4, 5], dtype=np.float32).reshape(-1,1)  # 2-D Matrix
Y_train = np.array([0,  0, 0, 1, 1, 1], dtype=np.float32).reshape(-1,1)  # 2-D Matrix

In [144]:
#logistic regression Sequential model
model = Sequential([tf.keras.layers.Dense(1,input_dim=1,activation='sigmoid',name='L1')])

In [145]:
#summary of modle
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ L1 (Dense)                      │ (None, 1)              │             2 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

In [146]:
#layer
logistic_layer =model.get_layer('L1')

In [147]:
#intilaize 
a2 = model.predict(X_train[0].reshape(1,1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step


In [150]:
#set w & b
set_w = np.array([[2]])
set_b = np.array([-4.5])
logistic_layer.set_weights([set_w, set_b])

In [151]:
#prediction 
prediction = model.predict(X_train)
print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
[[0.01098694]
 [0.07585818]
 [0.37754065]
 [0.8175745 ]
 [0.97068775]
 [0.99592984]]


In [155]:
for i in range(len(prediction)):
    
    if prediction[i] >= 0.5 :
        prediction[i] = 1
    else:
        prediction[i] = 0

print(prediction)

[[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]]
